// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRDeQboffZeqn6tV2H4IGHg0DeQik2CHk',
    appId: '1:1091345643449:web:d760114b2d823879ff2868',
    messagingSenderId: '1091345643449',
    projectId: 'mechatronics-app-52da8',
    authDomain: 'mechatronics-app-52da8.firebaseapp.com',
    storageBucket: 'mechatronics-app-52da8.appspot.com',
    measurementId: 'G-9TZE9SQGDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL-KlqxpKdd6wEkERBGR15DBiN5DCMI5g',
    appId: '1:1091345643449:android:e2084f55bd6af819ff2868',
    messagingSenderId: '1091345643449',
    projectId: 'mechatronics-app-52da8',
    storageBucket: 'mechatronics-app-52da8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqMoN_ezpjm80CENS09qxcadgpAQ6IG14',
    appId: '1:1091345643449:ios:bdddea487a398a26ff2868',
    messagingSenderId: '1091345643449',
    projectId: 'mechatronics-app-52da8',
    storageBucket: 'mechatronics-app-52da8.appspot.com',
    iosClientId: '1091345643449-niq2u1bnmpu739a2q5kbp9dtkqmng558.apps.googleusercontent.com',
    iosBundleId: 'futo.mechatronics.com.mCe',
  );
}
